name: frontend_test

on:
  push:
    branches:
      - master

jobs:
  frontend_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run test
        working-directory: ./backend
        run: ./gradlew clean test
