name: deploy_docker

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          context: frontend/
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: glitchless/secret-santa-frontend:latest, glitchless/secret-santa-frontend:${{ github.run_number }}
      - name: Build and push backend
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: backend/
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: glitchless/secret-santa-backend:latest, glitchless/secret-santa-backend:${{ github.run_number }}
