name: deploy_frontend

on:
  push:
    branches:
      - master

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          context: frontend/
          push: true
          tags: glitchless/secret-santa-frontend:latest, glitchless/secret-santa-frontend:${{ github.run_number }}
