name: frontend_test

on:
  push:
    branches:
      - master

jobs:
  frontend_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm ci --prefer-offline --no-audit --cache .npm
      - run: npm run lint
