name: frontend_lint

on:
  push:
    branches:
      - master

jobs:
  frontend_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - working-directory: ./frontend
        run: npm ci --prefer-offline --no-audit --cache .npm
      - working-directory: ./frontend
        run: npm run lint
